// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ping.proto

package ping

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// リクエストの内容定義
type HelloRequest struct {
	ToMessage            string   `protobuf:"bytes,1,opt,name=toMessage,proto3" json:"toMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d51d96c3ad891f5, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetToMessage() string {
	if m != nil {
		return m.ToMessage
	}
	return ""
}

type GoodbyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoodbyRequest) Reset()         { *m = GoodbyRequest{} }
func (m *GoodbyRequest) String() string { return proto.CompactTextString(m) }
func (*GoodbyRequest) ProtoMessage()    {}
func (*GoodbyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d51d96c3ad891f5, []int{1}
}

func (m *GoodbyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoodbyRequest.Unmarshal(m, b)
}
func (m *GoodbyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoodbyRequest.Marshal(b, m, deterministic)
}
func (m *GoodbyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoodbyRequest.Merge(m, src)
}
func (m *GoodbyRequest) XXX_Size() int {
	return xxx_messageInfo_GoodbyRequest.Size(m)
}
func (m *GoodbyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GoodbyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GoodbyRequest proto.InternalMessageInfo

// レスポンス定義
type HelloResponse struct {
	ResMessage           string   `protobuf:"bytes,1,opt,name=resMessage,proto3" json:"resMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d51d96c3ad891f5, []int{2}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetResMessage() string {
	if m != nil {
		return m.ResMessage
	}
	return ""
}

type GoodbyResponse struct {
	ResMessage           string   `protobuf:"bytes,1,opt,name=resMessage,proto3" json:"resMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoodbyResponse) Reset()         { *m = GoodbyResponse{} }
func (m *GoodbyResponse) String() string { return proto.CompactTextString(m) }
func (*GoodbyResponse) ProtoMessage()    {}
func (*GoodbyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d51d96c3ad891f5, []int{3}
}

func (m *GoodbyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoodbyResponse.Unmarshal(m, b)
}
func (m *GoodbyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoodbyResponse.Marshal(b, m, deterministic)
}
func (m *GoodbyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoodbyResponse.Merge(m, src)
}
func (m *GoodbyResponse) XXX_Size() int {
	return xxx_messageInfo_GoodbyResponse.Size(m)
}
func (m *GoodbyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GoodbyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GoodbyResponse proto.InternalMessageInfo

func (m *GoodbyResponse) GetResMessage() string {
	if m != nil {
		return m.ResMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "ping.HelloRequest")
	proto.RegisterType((*GoodbyRequest)(nil), "ping.GoodbyRequest")
	proto.RegisterType((*HelloResponse)(nil), "ping.HelloResponse")
	proto.RegisterType((*GoodbyResponse)(nil), "ping.GoodbyResponse")
}

func init() { proto.RegisterFile("ping.proto", fileDescriptor_6d51d96c3ad891f5) }

var fileDescriptor_6d51d96c3ad891f5 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xc8, 0xcc, 0x4b,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x74, 0xb8, 0x78, 0x3c, 0x52,
	0x73, 0x72, 0xf2, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x64, 0xb8, 0x38, 0x4b, 0xf2,
	0x7d, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x10, 0x02,
	0x4a, 0xfc, 0x5c, 0xbc, 0xee, 0xf9, 0xf9, 0x29, 0x49, 0x95, 0x50, 0xe5, 0x4a, 0xfa, 0x5c, 0xbc,
	0x50, 0xed, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x72, 0x5c, 0x5c, 0x45, 0xa9, 0xc5, 0xa8,
	0x06, 0x20, 0x89, 0x28, 0x19, 0x70, 0xf1, 0xc1, 0x4c, 0x20, 0x4e, 0x87, 0x51, 0x21, 0x17, 0x4b,
	0x40, 0x66, 0x5e, 0xba, 0x90, 0x11, 0x17, 0x2b, 0xd8, 0x2a, 0x21, 0x21, 0x3d, 0xb0, 0x2f, 0x90,
	0x9d, 0x2d, 0x25, 0x8c, 0x22, 0x06, 0x31, 0x59, 0x89, 0x41, 0xc8, 0x94, 0x8b, 0x0d, 0x62, 0x9b,
	0x10, 0x54, 0x01, 0x8a, 0xeb, 0xa5, 0x44, 0x50, 0x05, 0x61, 0xda, 0x92, 0xd8, 0xc0, 0x21, 0x64,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x02, 0x16, 0xf1, 0x2f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PingClient is the client API for Ping service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PingClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	Goodby(ctx context.Context, in *GoodbyRequest, opts ...grpc.CallOption) (*GoodbyResponse, error)
}

type pingClient struct {
	cc *grpc.ClientConn
}

func NewPingClient(cc *grpc.ClientConn) PingClient {
	return &pingClient{cc}
}

func (c *pingClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/ping.Ping/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingClient) Goodby(ctx context.Context, in *GoodbyRequest, opts ...grpc.CallOption) (*GoodbyResponse, error) {
	out := new(GoodbyResponse)
	err := c.cc.Invoke(ctx, "/ping.Ping/Goodby", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PingServer is the server API for Ping service.
type PingServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	Goodby(context.Context, *GoodbyRequest) (*GoodbyResponse, error)
}

// UnimplementedPingServer can be embedded to have forward compatible implementations.
type UnimplementedPingServer struct {
}

func (*UnimplementedPingServer) Hello(ctx context.Context, req *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (*UnimplementedPingServer) Goodby(ctx context.Context, req *GoodbyRequest) (*GoodbyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Goodby not implemented")
}

func RegisterPingServer(s *grpc.Server, srv PingServer) {
	s.RegisterService(&_Ping_serviceDesc, srv)
}

func _Ping_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ping.Ping/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ping_Goodby_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodbyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServer).Goodby(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ping.Ping/Goodby",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServer).Goodby(ctx, req.(*GoodbyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ping_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ping.Ping",
	HandlerType: (*PingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Ping_Hello_Handler,
		},
		{
			MethodName: "Goodby",
			Handler:    _Ping_Goodby_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ping.proto",
}
